---
title: "Danceability of Beyonce Albums"
author: 
  - Francesca Ye
thanks: "Code and data are available at: https://github.com/Francesca-Ye/beyonce"
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(spotifyr)
```


# Introduction

# Data {#sec-data}

```{r}
#| echo: false
beyonce <-
  readRDS("~/beyonce/data/raw_data/beyonce.rds")
```
@fig-beyonce
```{r}
#| label: fig-beyonce
#| fig-cap: Danceability of Beyonce Albums Over Time
#| echo: false
#| fig-pos: "H"
beyonce <-
  as_tibble(beyonce)

beyonce |>
  filter(album_release_date_precision == "day") |>
  mutate(album_release_date = ymd(album_release_date)) |>
  ggplot(aes(
    x = album_release_date,
    y = danceability,
    group = album_release_date
  )) +
  geom_point(alpha = 0.5) +
  theme_minimal() +
  labs(x = "Album release date",
       y = "Danceability")
```

```{r}
#| label: tbl-beyonce
#| fig-cap: Average Danceability of Each Beyonce Album
#| echo: false

beyonce <-
  as_tibble(beyonce)

beyonce |>
  filter(album_release_date_precision == "day") |> 
  mutate(album_release_date = ymd(album_release_date)) |>
  summarize(ave_danceability = mean(danceability), .by = "album_name") |> 
  knitr::kable(
    col.names = c("Album", "Average danceability"),
    digits = 3,
    booktabs = TRUE,
    linesep = ""
  )
```

\newpage

\appendix

# Appendix {-}



\newpage


# References


